Repository Pritish-Sinha/Machine-Leaning-Project, pull requests merged in 2022-10, with the labels that each got.

#7 Create Titanic Survival Analysis
  Titanic Survival Analysis/Titanic_Survivors.ipynb
  tutorials/home-rentals.md
Labels: hacktoberfest-accepted

#9 Added the new projects to the readme file.
  README.md
Labels: hacktoberfest-accepted

#14 Add README.md
  Titanic Survival Analysis/README.md
Labels: documentation, hacktoberfest-accepted

#15 Update README.md
  BitCoin-Price-Prediction/README.md
Labels: documentation, hacktoberfest-accepted

#17 Add Twitter Sentiment Analysis
  twitter_sentiment_analysis/README.md
  twitter_sentiment_analysis/code_sentiment_analysis.ipynb
  twitter_sentiment_analysis/test_tweets_anuFYb8.csv
  twitter_sentiment_analysis/train_E6oV3lV.csv
Labels: good first issue, hacktoberfest-accepted
